
package com.smartcity.orchestrator.soapclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AirQualityService", targetNamespace = "http://service.airsoap.smartcity.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AirQualityService {


    /**
     * 
     * @param zone
     * @return
     *     returns com.smartcity.orchestrator.soapclient.AirQualityData
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAirQualityByZone", targetNamespace = "http://service.airsoap.smartcity.com/", className = "com.smartcity.orchestrator.soapclient.GetAirQualityByZone")
    @ResponseWrapper(localName = "getAirQualityByZoneResponse", targetNamespace = "http://service.airsoap.smartcity.com/", className = "com.smartcity.orchestrator.soapclient.GetAirQualityByZoneResponse")
    @Action(input = "http://service.airsoap.smartcity.com/AirQualityService/getAirQualityByZoneRequest", output = "http://service.airsoap.smartcity.com/AirQualityService/getAirQualityByZoneResponse")
    public AirQualityData getAirQualityByZone(
        @WebParam(name = "zone", targetNamespace = "")
        String zone);

}
