
package com.smartcity.orchestrator.soapclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AirQualityServiceImplService", targetNamespace = "http://service.airsoap.smartcity.com/", wsdlLocation = "http://localhost:8082/air-quality?wsdl")
public class AirQualityServiceImplService
    extends Service
{

    private final static URL AIRQUALITYSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException AIRQUALITYSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName AIRQUALITYSERVICEIMPLSERVICE_QNAME = new QName("http://service.airsoap.smartcity.com/", "AirQualityServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/air-quality?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AIRQUALITYSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        AIRQUALITYSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public AirQualityServiceImplService() {
        super(__getWsdlLocation(), AIRQUALITYSERVICEIMPLSERVICE_QNAME);
    }

    public AirQualityServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AIRQUALITYSERVICEIMPLSERVICE_QNAME, features);
    }

    public AirQualityServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, AIRQUALITYSERVICEIMPLSERVICE_QNAME);
    }

    public AirQualityServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AIRQUALITYSERVICEIMPLSERVICE_QNAME, features);
    }

    public AirQualityServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AirQualityServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AirQualityService
     */
    @WebEndpoint(name = "AirQualityServiceImplPort")
    public AirQualityService getAirQualityServiceImplPort() {
        return super.getPort(new QName("http://service.airsoap.smartcity.com/", "AirQualityServiceImplPort"), AirQualityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AirQualityService
     */
    @WebEndpoint(name = "AirQualityServiceImplPort")
    public AirQualityService getAirQualityServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.airsoap.smartcity.com/", "AirQualityServiceImplPort"), AirQualityService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AIRQUALITYSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw AIRQUALITYSERVICEIMPLSERVICE_EXCEPTION;
        }
        return AIRQUALITYSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
